name: ctse_quotes_flutter_app
description: Quotes app using flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
  random_color: ^1.0.6-nullsafety
  google_fonts: ^2.3.1
  flutter_screenutil: ^5.3.1
  flutter_tts: ^3.3.3
  clipboard: ^0.1.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login.svg
    - assets/registration.svg
    - assets/home.svg
    - assets/quote_icon.png

